# Generated by Django 2.0 on 2019-06-25 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('water_mark', models.FileField(blank=True, null=True, upload_to='station/water_marks/')),
                ('coordinates', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('locality', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=32)),
                ('embed_code', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dealers.Dealer')),
            ],
        ),
        migrations.CreateModel(
            name='StationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color_name', models.CharField(blank=True, max_length=32)),
                ('color_hex_code', models.CharField(blank=True, max_length=7)),
                ('details', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.Rate')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='station_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.StationClass'),
        ),
    ]
