# Generated by Django 2.0 on 2019-06-25 07:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='transactions/files/input_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'pdf'))])),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='transactions/files/converted_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'pdf'))])),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('has_error', models.BooleanField(default=False)),
                ('file_type', models.CharField(blank=True, choices=[('jpg', 'JPG'), ('png', 'PNG'), ('pdf', 'PDF'), ('txt', 'TXT')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('otp_1', models.CharField(max_length=4)),
                ('otp_2', models.CharField(max_length=4)),
                ('payment_mode', models.CharField(choices=[('AC', 'Account'), ('CO', 'Coin')], max_length=2)),
                ('color_model', models.CharField(choices=[('BW', 'Black&White'), ('CL', 'Colorful')], default='BW', max_length=2)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pages', models.PositiveSmallIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_on', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_permitted', models.BooleanField(default=True)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.File')),
                ('printed_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stations.Station')),
                ('station_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stations.StationClass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
