# Generated by Django 2.0 on 2019-06-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference1',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
