# Generated by Django 2.0 on 2019-06-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_reference1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference1',
        ),
    ]
